# Generated by Django 5.2.15 on 2026-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["ordering", "order", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
