# Generated by Django 5.2.15 on 2026-06-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_category_options_category_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug_en",
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug_fr",
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="category",
            name="slug_rw",
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="meta_description_rw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="seo_title_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="seo_title_fr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="seo_title_rw",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug_en",
            field=models.SlugField(max_length=550, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug_fr",
            field=models.SlugField(max_length=550, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug_rw",
            field=models.SlugField(max_length=550, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_fr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_rw",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug_en",
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug_fr",
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="slug_rw",
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
    ]
