# Generated by Django 5.2.15 on 2026-06-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_post_english_complete_post_french_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="source_language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("fr", "French"), ("rw", "Kinyarwanda")],
                db_index=True,
                help_text="Primary imported/original language for this post.",
                max_length=5,
            ),
        ),
    ]
