# Generated by Django 5.2.15 on 2026-06-23 18:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(max_length=200)),
                ("site_name_en", models.CharField(max_length=200, null=True)),
                ("site_name_fr", models.CharField(max_length=200, null=True)),
                ("site_name_rw", models.CharField(max_length=200, null=True)),
                ("tagline", models.CharField(blank=True, max_length=500)),
                ("tagline_en", models.CharField(blank=True, max_length=500, null=True)),
                ("tagline_fr", models.CharField(blank=True, max_length=500, null=True)),
                ("tagline_rw", models.CharField(blank=True, max_length=500, null=True)),
                ("logo", models.ImageField(blank=True, upload_to="site/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/")),
                ("footer_text", ckeditor.fields.RichTextField(blank=True)),
                (
                    "footer_text_en",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "footer_text_fr",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "footer_text_rw",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("title_rw", models.CharField(max_length=200, null=True)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Slider"),
                            ("featured", "Featured Posts"),
                            ("latest", "Latest Posts"),
                            ("category", "Category Posts"),
                            ("popular", "Popular Posts"),
                            ("newsletter", "Newsletter Block"),
                        ],
                        default="latest",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("post_count", models.IntegerField(default=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage Section",
                "verbose_name_plural": "Homepage Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("title_rw", models.CharField(max_length=200, null=True)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="External URL or internal path",
                        max_length=500,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                (
                    "subtitle_en",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "subtitle_fr",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "subtitle_rw",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image", models.ImageField(upload_to="sliders/")),
                ("link_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slider",
                "verbose_name_plural": "Sliders",
                "ordering": ["order"],
            },
        ),
    ]
