# Generated by Django 5.2.15 on 2026-06-23 19:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("title_rw", models.CharField(max_length=200, null=True)),
                ("image", models.ImageField(upload_to="advertisements/")),
                (
                    "mobile_image",
                    models.ImageField(blank=True, upload_to="advertisements/"),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("home_top", "Home top"),
                            ("home_after_featured", "Home after featured"),
                            ("home_middle", "Home middle"),
                            ("sidebar", "Sidebar"),
                            ("article_top", "Article top"),
                            ("article_bottom", "Article bottom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("desktop_width", models.PositiveIntegerField(default=970)),
                ("desktop_height", models.PositiveIntegerField(default=90)),
                ("mobile_width", models.PositiveIntegerField(default=320)),
                ("mobile_height", models.PositiveIntegerField(default=100)),
                ("clicks", models.PositiveIntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_fr", models.CharField(max_length=200, null=True)),
                ("name_rw", models.CharField(max_length=200, null=True)),
                ("logo", models.ImageField(upload_to="partners/")),
                ("website_url", models.URLField(blank=True)),
                ("ordering", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_text_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_text_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_text_rw",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="button_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="content_en",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="content_fr",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="content_rw",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="image",
            field=models.ImageField(blank=True, upload_to="homepage/"),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="key",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle_fr",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="homepagesection",
            name="subtitle_rw",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="open_in_new_tab",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_1_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_1_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_1_rw",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_2_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_2_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="address_line_2_rw",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="copyright_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="copyright_text_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="copyright_text_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="copyright_text_rw",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="footer_logo",
            field=models.ImageField(blank=True, upload_to="site/"),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="phone_1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="phone_2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="phone_3",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="x_url",
            field=models.URLField(blank=True),
        ),
    ]
