# Generated by Django 5.2.15 on 2026-06-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_advertisement_partner_homepagesection_button_text_and_more"),
        ("pages", "0002_page_excerpt_page_excerpt_en_page_excerpt_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="default_language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("rw", "Kinyarwanda")],
                default="en",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="sitesetting",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("title_rw", models.CharField(max_length=200, null=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("url_en", models.CharField(blank=True, max_length=500, null=True)),
                ("url_fr", models.CharField(blank=True, max_length=500, null=True)),
                ("url_rw", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("topbar", "Top bar"),
                            ("main_menu", "Main menu"),
                            ("footer_quick_links", "Footer quick links"),
                        ],
                        default="main_menu",
                        max_length=30,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="pages.page",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["location", "order", "title"],
            },
        ),
    ]
