# Generated by Django 5.2.15 on 2026-06-23 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0003_sitesetting_default_language_sitesetting_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_url", models.URLField(max_length=1000, unique=True)),
                ("new_url", models.CharField(max_length=1000)),
                (
                    "source_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("rw", "Kinyarwanda"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content_type_name", models.CharField(blank=True, max_length=50)),
                (
                    "old_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["old_url"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("file", models.FileField(blank=True, upload_to="wordpress/")),
                ("remote_url", models.URLField(blank=True, max_length=1000)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("alt_text", models.CharField(blank=True, max_length=500)),
                ("caption", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("source_database", models.CharField(max_length=100)),
                ("source_language", models.CharField(max_length=10)),
                ("old_wordpress_id", models.PositiveBigIntegerField()),
                ("old_file_path", models.CharField(blank=True, max_length=1000)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                ("is_missing", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-uploaded_at", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_database", "old_wordpress_id"),
                        name="unique_wordpress_media_asset",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_database", models.CharField(max_length=100)),
                ("source_language", models.CharField(max_length=10)),
                ("source_type", models.CharField(max_length=50)),
                ("old_wordpress_id", models.PositiveBigIntegerField()),
                ("old_url", models.URLField(blank=True, max_length=1000)),
                ("object_id", models.PositiveBigIntegerField()),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("imported", "Imported"),
                            ("updated", "Updated"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                        ],
                        default="imported",
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_import_content_9256c8_idx",
                    ),
                    models.Index(
                        fields=["source_language", "source_type"],
                        name="core_import_source__1e8c6e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_database", "source_type", "old_wordpress_id"),
                        name="unique_wordpress_import_source",
                    )
                ],
            },
        ),
    ]
