# Generated by Django 5.2.15 on 2026-06-23 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("news", "0003_category_slug_en_category_slug_fr_category_slug_rw_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="old_wordpress_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="source_database",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="comment",
            name="source_language",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("old_wordpress_id__isnull", False)),
                fields=("source_database", "old_wordpress_id"),
                name="unique_imported_wordpress_comment",
            ),
        ),
    ]
