# Generated by Django 5.2.15 on 2026-06-23 18:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("title_en", models.CharField(max_length=500, null=True)),
                ("title_fr", models.CharField(max_length=500, null=True)),
                ("title_rw", models.CharField(max_length=500, null=True)),
                ("slug", models.SlugField(max_length=550, unique=True)),
                ("content", ckeditor.fields.RichTextField()),
                ("content_en", ckeditor.fields.RichTextField(null=True)),
                ("content_fr", ckeditor.fields.RichTextField(null=True)),
                ("content_rw", ckeditor.fields.RichTextField(null=True)),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("featured_image", models.ImageField(blank=True, upload_to="pages/")),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["order", "title"],
            },
        ),
    ]
