# Generated by Django 5.2.15 on 2026-06-23 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="page",
            name="excerpt_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="excerpt_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="excerpt_rw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_description_rw",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_fr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="meta_title_rw",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="pages.page",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="show_in_menu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="slug_en",
            field=models.SlugField(max_length=550, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="page",
            name="slug_fr",
            field=models.SlugField(max_length=550, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="page",
            name="slug_rw",
            field=models.SlugField(max_length=550, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="page",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("default", "Default page"),
                    ("contact", "Contact"),
                    ("donate", "Donate"),
                    ("find_counsellor", "Find a counsellor"),
                    ("policy", "Policy"),
                ],
                default="default",
                max_length=30,
            ),
        ),
    ]
