# Generated by Django 5.2.15 on 2026-06-23 21:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_page_excerpt_page_excerpt_en_page_excerpt_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("name_en", models.CharField(max_length=150, null=True)),
                ("name_fr", models.CharField(max_length=150, null=True)),
                ("name_rw", models.CharField(max_length=150, null=True)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_rw", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Book categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounsellingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("rw", "Kinyarwanda"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "counselling_type",
                    models.CharField(
                        choices=[
                            ("spiritual", "Spiritual counselling"),
                            ("family", "Family counselling"),
                            ("healing", "Healing support"),
                            ("leadership", "Leadership guidance"),
                            ("general", "General support"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("in_progress", "In progress"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DonationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_fr", models.CharField(max_length=200, null=True)),
                ("name_rw", models.CharField(max_length=200, null=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank transfer"),
                            ("mobile_money", "Mobile money"),
                            ("online", "Online payment"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("account_name", models.CharField(blank=True, max_length=200)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("mobile_money_number", models.CharField(blank=True, max_length=50)),
                ("instructions", models.TextField(blank=True)),
                ("instructions_en", models.TextField(blank=True, null=True)),
                ("instructions_fr", models.TextField(blank=True, null=True)),
                ("instructions_rw", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DonationPledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="RWF", max_length=10)),
                (
                    "donation_purpose",
                    models.CharField(
                        choices=[
                            ("general", "General ministry support"),
                            ("publications", "Publications"),
                            ("counselling", "Counselling"),
                            ("books", "Books/resources"),
                            ("outreach", "Community outreach"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadershipMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=200)),
                ("role_en", models.CharField(max_length=200, null=True)),
                ("role_fr", models.CharField(max_length=200, null=True)),
                ("role_rw", models.CharField(max_length=200, null=True)),
                ("photo", models.ImageField(blank=True, upload_to="leadership/")),
                ("bio", ckeditor.fields.RichTextField(blank=True)),
                ("bio_en", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("bio_fr", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("bio_rw", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("facebook_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="page",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("default", "Default page"),
                    ("who_we_are", "Who we are"),
                    ("our_history", "Our history"),
                    ("mission_and_vision", "Mission and vision"),
                    ("leadership", "Leadership"),
                    ("what_we_do", "What we do"),
                    ("books", "Books"),
                    ("contact", "Contact"),
                    ("donate", "Donate"),
                    ("find_counsellor", "Find a counsellor"),
                    ("policy", "Policy"),
                ],
                default="default",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("title_en", models.CharField(max_length=300, null=True)),
                ("title_fr", models.CharField(max_length=300, null=True)),
                ("title_rw", models.CharField(max_length=300, null=True)),
                ("slug", models.SlugField(max_length=350, unique=True)),
                ("cover_image", models.ImageField(blank=True, upload_to="books/")),
                ("author", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                (
                    "description_en",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "description_fr",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "description_rw",
                    ckeditor.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("rw", "Kinyarwanda"),
                            ("multi", "Multilingual"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_free", models.BooleanField(default=False)),
                (
                    "download_file",
                    models.FileField(blank=True, upload_to="books/files/"),
                ),
                ("external_link", models.URLField(blank=True)),
                ("published_at", models.DateField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="pages.bookcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-published_at", "title"],
            },
        ),
    ]
