# Generated by Django 5.2.15 on 2026-06-24 05:46

from django.db import migrations, models
from django.utils.text import slugify


def populate_leadership_slugs(apps, schema_editor):
    LeadershipMember = apps.get_model("pages", "LeadershipMember")
    for member in LeadershipMember.objects.all():
        changed = []
        if not member.slug:
            base = slugify(getattr(member, "name_en", None) or member.name) or f"member-{member.pk}"
            slug = base
            counter = 1
            while LeadershipMember.objects.filter(slug=slug).exclude(pk=member.pk).exists():
                slug = f"{base}-{counter}"
                counter += 1
            member.slug = slug
            changed.append("slug")
        if not getattr(member, "name_en", None):
            member.name_en = member.name
            changed.append("name_en")
        if not getattr(member, "role_en", None):
            member.role_en = member.role
            changed.append("role_en")
        if changed:
            member.save(update_fields=changed)


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_bookcategory_contactmessage_counsellingrequest_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leadershipmember",
            options={
                "ordering": ["order", "name"],
                "verbose_name": "Leadership team member",
                "verbose_name_plural": "Leadership team members",
            },
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="external_photo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="name_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="name_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="name_rw",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="slug",
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="leadershipmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="leadershipmember",
            name="photo",
            field=models.ImageField(blank=True, upload_to="team/"),
        ),
        migrations.RunPython(populate_leadership_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="leadershipmember",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
