"""Registry mapping dashboard modules to models, forms, and URL names."""

from django.utils.translation import gettext_lazy as _

from apps.comments.models import Comment
from apps.core.models import Advertisement, HomepageSection, MenuItem, Partner, SiteSetting
from apps.news.models import Category, Tag
from apps.newsletter.models import Subscriber
from apps.pages.models import Book, ContactMessage, CounsellingRequest, Counsellor, DonationPledge, Page

from .forms_modules import (
    AdvertisementDashboardForm,
    BookDashboardForm,
    CategoryDashboardForm,
    CommentDashboardForm,
    ContactDashboardForm,
    CounsellingDashboardForm,
    DonationDashboardForm,
    HomepageSectionDashboardForm,
    MenuItemDashboardForm,
    PageDashboardForm,
    PartnerDashboardForm,
    SiteSettingDashboardForm,
    SubscriberDashboardForm,
    TagDashboardForm,
)


MODULE_REGISTRY = {
    "pages": {
        "module_key": "pages",
        "model": Page,
        "form_class": PageDashboardForm,
        "list_url_name": "dashboard:page_list",
        "create_url_name": "dashboard:page_create",
        "edit_url_name": "dashboard:page_edit",
        "delete_url_name": "dashboard:page_delete",
        "singular": _("Page"),
        "allow_create": True,
        "allow_delete": True,
        "readonly_fields": [],
    },
    "categories": {
        "module_key": "categories",
        "model": Category,
        "form_class": CategoryDashboardForm,
        "list_url_name": "dashboard:category_list",
        "create_url_name": "dashboard:category_create",
        "edit_url_name": "dashboard:category_edit",
        "delete_url_name": "dashboard:category_delete",
        "singular": _("Category"),
        "allow_create": True,
        "allow_delete": True,
    },
    "tags": {
        "module_key": "tags",
        "model": Tag,
        "form_class": TagDashboardForm,
        "list_url_name": "dashboard:tag_list",
        "create_url_name": "dashboard:tag_create",
        "edit_url_name": "dashboard:tag_edit",
        "delete_url_name": "dashboard:tag_delete",
        "singular": _("Tag"),
        "allow_create": True,
        "allow_delete": True,
    },
    "comments": {
        "module_key": "comments",
        "model": Comment,
        "form_class": CommentDashboardForm,
        "list_url_name": "dashboard:comment_list",
        "create_url_name": None,
        "edit_url_name": "dashboard:comment_edit",
        "delete_url_name": "dashboard:comment_delete",
        "singular": _("Comment"),
        "allow_create": False,
        "allow_delete": True,
    },
    "books": {
        "module_key": "books",
        "model": Book,
        "form_class": BookDashboardForm,
        "list_url_name": "dashboard:book_list",
        "create_url_name": "dashboard:book_create",
        "edit_url_name": "dashboard:book_edit",
        "delete_url_name": "dashboard:book_delete",
        "singular": _("Book"),
        "allow_create": True,
        "allow_delete": True,
    },
    "counselling": {
        "module_key": "counselling",
        "model": CounsellingRequest,
        "form_class": CounsellingDashboardForm,
        "list_url_name": "dashboard:counselling_requests",
        "create_url_name": None,
        "edit_url_name": "dashboard:counselling_request_edit",
        "delete_url_name": "dashboard:counselling_delete",
        "singular": _("Counselling Request"),
        "allow_create": False,
        "allow_delete": True,
        "submission_detail": True,
    },
    "contact": {
        "module_key": "contact",
        "model": ContactMessage,
        "form_class": ContactDashboardForm,
        "list_url_name": "dashboard:contact_list",
        "create_url_name": None,
        "edit_url_name": "dashboard:contact_edit",
        "delete_url_name": "dashboard:contact_delete",
        "singular": _("Contact Message"),
        "allow_create": False,
        "allow_delete": True,
        "submission_detail": True,
    },
    "donations": {
        "module_key": "donations",
        "model": DonationPledge,
        "form_class": DonationDashboardForm,
        "list_url_name": "dashboard:donation_list",
        "create_url_name": None,
        "edit_url_name": "dashboard:donation_pledge_edit",
        "delete_url_name": None,
        "singular": _("Donation Pledge"),
        "allow_create": False,
        "allow_delete": True,
        "submission_detail": True,
    },
    "ads": {
        "module_key": "ads",
        "model": Advertisement,
        "form_class": AdvertisementDashboardForm,
        "list_url_name": "dashboard:ad_list",
        "create_url_name": "dashboard:ad_create",
        "edit_url_name": "dashboard:ad_edit",
        "delete_url_name": "dashboard:ad_delete",
        "singular": _("Advertisement"),
        "allow_create": True,
        "allow_delete": True,
    },
    "partners": {
        "module_key": "partners",
        "model": Partner,
        "form_class": PartnerDashboardForm,
        "list_url_name": "dashboard:partner_list",
        "create_url_name": "dashboard:partner_create",
        "edit_url_name": "dashboard:partner_edit",
        "delete_url_name": "dashboard:partner_delete",
        "singular": _("Partner"),
        "allow_create": True,
        "allow_delete": True,
    },
    "menus": {
        "module_key": "menus",
        "model": MenuItem,
        "form_class": MenuItemDashboardForm,
        "list_url_name": "dashboard:menu_list",
        "create_url_name": "dashboard:menu_create",
        "edit_url_name": "dashboard:menu_edit",
        "delete_url_name": "dashboard:menu_delete",
        "singular": _("Menu Item"),
        "allow_create": True,
        "allow_delete": True,
    },
    "homepage": {
        "module_key": "homepage",
        "model": HomepageSection,
        "form_class": HomepageSectionDashboardForm,
        "list_url_name": "dashboard:homepage_list",
        "create_url_name": "dashboard:homepage_create",
        "edit_url_name": "dashboard:homepage_edit",
        "delete_url_name": "dashboard:homepage_delete",
        "singular": _("Homepage Section"),
        "allow_create": True,
        "allow_delete": True,
    },
    "subscribers": {
        "module_key": "subscribers",
        "model": Subscriber,
        "form_class": SubscriberDashboardForm,
        "list_url_name": "dashboard:subscriber_list",
        "create_url_name": "dashboard:subscriber_create",
        "edit_url_name": "dashboard:subscriber_edit",
        "delete_url_name": "dashboard:subscriber_delete",
        "singular": _("Subscriber"),
        "allow_create": True,
        "allow_delete": True,
    },
    "settings": {
        "module_key": "settings",
        "model": SiteSetting,
        "form_class": SiteSettingDashboardForm,
        "list_url_name": "dashboard:settings",
        "create_url_name": None,
        "edit_url_name": "dashboard:settings",
        "delete_url_name": None,
        "singular": _("Site Settings"),
        "allow_create": False,
        "allow_delete": False,
        "singleton": True,
    },
}


def get_module_config(registry_key):
    if registry_key not in MODULE_REGISTRY:
        raise KeyError(f"Unknown module: {registry_key}")
    return MODULE_REGISTRY[registry_key]
